### ISSUE TITLE
experiment

### ISSUE THREAD

**Issue by fukexue** [yichen928/STRL#1]
I'm sorry to bother you. Are the classification experiments in your paper under 2048 points?

**Comment by yichen928** [comment]
The linear SVM classification experiment is under 2048 points. The DGCNN fine-tuning experiment is under 1024 points. We just follow the setting of some previous research.

**Comment by fukexue** [comment]
Thank you very much. I have another little puzzle, I saw that ACC in dgcnn's original article is 92.9. Is the result 92.2 reported in your article the result of retraining?

**Comment by yichen928** [comment]
The [pytorch implementation](https://github.com/WangYueFt/dgcnn/tree/master/pytorch) of DGCNN can only reach about 92.2, so we use it as our baseline. You can refer to some [issues](https://github.com/WangYueFt/dgcnn/issues) in this repo about this problem.
