### ISSUE TITLE
weight model error

### ISSUE THREAD

**Issue by fukexue** [yichen928/STRL#2]
this weight raise a error when load it to model. 
```
 RuntimeError: unexpected EOF, expected 9781136 more bytes. The file might be corrupted.
terminate called without an active exception
```
https://drive.google.com/file/d/1NzFKTyw_TfZQon902IqEnldODYgWKvlG/view?usp=sharing

**Comment by yichen928** [comment]
Sorry, the file is broken. I will re-upload it as soon as possible.

**Comment by fukexue** [comment]
Is the weight model available?

**Comment by yichen928** [comment]
The e-mail has been sent. And I have re-uploaded all the broken weights.
