### ISSUE TITLE
When will the outdoor detection related codes be available?

### ISSUE THREAD

**Issue by JenningsL** [yichen928/STRL#5]
Thanks for your great work! Looking forward to try out this method on outdoor 3D detection task, may I ask when will you release the related codes?

**Comment by JenningsL** [comment]
Also, the file scannet_test.pickle is missing. Could you provide these files or instructions to generate them?

**Comment by yichen928** [comment]
I am very sorry for this late reply. For scannet_test.pickle, you can download it here: https://shapenet.cs.stanford.edu/media/scannet_data_pointnet2.zip.

For the outdoor scenes, we are sorry that this part code is quite messy. We will try to sort it out and release it later.
