### ISSUE TITLE
Question about the PVRCNN model in outdoor scenes

### ISSUE THREAD

**Issue by lichengwei-code** [yichen928/STRL#7]
Hi !
Thanks for your great job for model pretraining on point clouds,  I have a  question about the outdoor scenes model, PVRCNN.  Unlike the indoor scenes model VoteNet,  the PVRCNN is a more complex model with two stages. So my question is where the max pooling is applied for the PVRCNN model,  3D backbone or 2D backbone? 
Thanks for your reply!

**Comment by yichen928** [comment]
Hello, thank you for your interest. We add the pooling layer to the location of the red arrow, and only the red part (voxelization+3D sparse convolution backbone) is pretrained. 
![image](https://user-images.githubusercontent.com/48796750/150629811-fe0f35be-7407-4bb7-812b-d962d111f73e.png)

**Comment by JinSeoung-Oh** [comment]
Hello~
At first, I want say thanks for your great and creative job.
After read this issue, I have a question about STRL+PVRCNN
According to your answer, your model looks like just adding pooling layer on 3D Sparse convolution part of original PVRCNN model.
If then, why this model is STRL "+" PVRCNN model? I mean, What is role of SRTL (or BYON) in outdoor scene understanding part? 
Thanks~


+++++
Never mind
I figured out it from your paper.
Sorry..
